name: teste google
on: [push, workflow_dispatch]

jobs:
  Run-tests:
    runs-on: ubuntu-latest

    steps:  
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chrome WebDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget -q https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Execute tests
        run: robot testes.robot