name: teste google
on: [push, workflow_dispatch]

jobs:
  Run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute tests
        run: |
        google-chrome --user-data-dir=/tmp/chrome-profile --headless --disable-gpu --remote-debugging-port=9222 &
        robot testes.robot
        pkill chrome